### ISSUE TITLE
App requires SDK version 33

### ISSUE THREAD

**Issue by vedudx** [CMPUT301F22T08/AndroidImpact#103]
- Some of our code strictly requires android SDK version 33, so I am wondering if it's a good idea to change min SDK version to be 33 which is our target version. 
- During testing today, app crashed in kailash's phone which uses SDK version 32 but works fine in emulator. This is something we have to keep in mind for demo as well

**Comment by joshuanianji** [comment]
I would prefer using mimimum sdk 33, I was about to use it in #81.

Ended up deciding against that because it broke CI and didn't work on some people's computers, but it would help because it can prevent us using deprecated methods.

I would prefer we update min SDK to 33 though, but the entire team has to be on board.

**Comment by joshuanianji** [comment]
Since Curtis' phone has SDK 31, we should probably keep it as is. Closing for now...
