### ISSUE TITLE
Compile error when generating JavaDocs: android packages do not exist

### ISSUE THREAD

**Issue by kailashs2002** [CMPUT301F22T08/AndroidImpact#32]
When generating the javadoc for the app, I am gettting compile errors under MainActivity that say that the following packages cannot be found:
 - android.content
 - android.os
 - android.view
 - android.widget
Anyone else having this issue?

**Comment by joshuanianji** [comment]
I don't have this error now, can you send a screenshot?

**Comment by joshuanianji** [comment]
Looks like we somehow need to link it to android jar file, like in Lab 6.

This [slack overflow answer](https://stackoverflow.com/a/55519228) has something similar, maybe we can try this in #33 ?

**Comment by joshuanianji** [comment]
Ok, turns out this is pretty complicated and I haven't had the time to figure out something concrete. The current solution is as follows (and only works on my machine):

1. uncomment `implementation files('/Users/joshuaji/Library/Android/sdk/platforms/android-33/android.jar')` in `app/build.gradle`
2. Sync gradle
3. Generate javadoc
4. Comment the line again
5. Sync gradle

CI script will fail if the line is uncommented, and i can't find a way to run the javadoc command in a CLI, due to some [autogenerated stuff Android Studio makes](https://stackoverflow.com/questions/70629252/how-to-generate-javadocs-via-android-studio-headlessly).
